### ISSUE TITLE
I already have wsol in the picture below, but I still get an error ERROR: SOL token account not found in wallet: 5wHpzo

### ISSUE THREAD

**Issue by lonely1215225** [warp-id/solana-trading-bot#106]
ERROR: SOL token account not found in wallet: 5wHpzo

<img width="347" alt="image" src="https://github.com/warp-id/solana-trading-bot/assets/44398275/7bef8dc2-5d67-4f06-998b-545f39ef9b92">

**Comment by lonely1215225** [comment]
I found the problem, it's rpc, it's best to use your own！

**Comment by Jelmaansuri** [comment]
Which RPC did you use, i have WSOL/USDC. Im using helius RPC btw
