### ISSUE TITLE
after installing all dependencies i got this Cannot find module '@metaplex-foundation/umi/serializers'

### ISSUE THREAD

**Issue by noorshanu** [warp-id/solana-trading-bot#128]
TSError: ⨯ Unable to compile TypeScript:
filters/mutable.filter.ts:6:28 - error TS2307: Cannot find module '@metaplex-foundation/umi/serializers' or its corresponding type declarations.

6 import { Serializer } from '@metaplex-foundation/umi/serializers';

**Comment by edujr1** [comment]
What is your Node Verions?

> TSError: ⨯ Unable to compile TypeScript: filters/mutable.filter.ts:6:28 - error TS2307: Cannot find module '@metaplex-foundation/umi/serializers' or its corresponding type declarations.
> 
> 6 import { Serializer } from '@metaplex-foundation/umi/serializers';

**Comment by noorshanu** [comment]
> What is your Node Verions?
> 
> > TSError: ⨯ Unable to compile TypeScript: filters/mutable.filter.ts:6:28 - error TS2307: Cannot find module '@metaplex-foundation/umi/serializers' or its corresponding type declarations.
> > 6 import { Serializer } from '@metaplex-foundation/umi/serializers';

I figured it out in mac just sudo -s then npm install and npm run start it works fine thanks

**Comment by pedrocastellanos** [comment]
I got same error in Windows. I' m using Node 20.14.0 and Yarn 
return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
filters/mutable.filter.ts:6:28 - error TS2307: Cannot find module '@metaplex-foundation/umi/serializers' or its corresponding type declarations.

6 import { Serializer } from '@metaplex-foundation/umi/serializers';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by noorshanu** [comment]
> I figured it out in mac just sudo -s then npm install and npm run start it works fine thanks

I figured it out in mac just sudo -s then npm install and npm run start it works fine thanks
