### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Othmantork** [warp-id/solana-trading-bot#143]
Can someone add pump.fun or https://dexscreener.com/moonshot Our money has dried up from the rug pull on Raydium 🥺🤡

**Comment by bologer** [comment]
@Othmantork unfortunately you won't be rug free with any bot, but you can always choose good bot + quick node to quickly enter and exit trades to avoid most of the rugs. I was doing a lot of research over the past few months Anita/Zenith seemed to be the best (there are hundreds of those tbh). Anita was offering free version and than switched to NFT model, where you buy their NFT and have access to the bot. I decided to search for something else. Right now I really anticipate release of primelabs bot - https://t.me/prime_labs. They have raydium and plan to add pump.fun support as well.
