### ISSUE TITLE
ERROR: SOL token account not found in wallet:

### ISSUE THREAD

**Issue by khalilshamdan** [warp-id/solana-trading-bot#166]
I am trying to test the bot on a wallet on devnet and keep getting this error even though  

spl-token accounts
Token                                         Balance   
--------------------------------------------------------
So11111111111111111111111111111111111111112   0.99796072

and 

solana balance
1.99646 SOL

this is my connection config
```
# Connection
RPC_ENDPOINT=https://solana-devnet.quicknode.io  
RPC_WEBSOCKET_ENDPOINT=wss://solana-devnet.quicknode.io 
COMMITMENT_LEVEL=processed 
```

```
# Bot
LOG_LEVEL=trace
ONE_TOKEN_AT_A_TIME=true
PRE_LOAD_EXISTING_MARKETS=false
CACHE_NEW_MARKETS=false
# default or warp or jito
TRANSACTION_EXECUTOR=warp
# if using default executor, fee below will be applied
COMPUTE_UNIT_LIMIT=101337
COMPUTE_UNIT_PRICE=421197
# if using warp or jito executor, fee below will be applied
CUSTOM_FEE=0.006

# Buy
QUOTE_MINT=WSOL
QUOTE_AMOUNT=0.05
AUTO_BUY_DELAY=0
MAX_BUY_RETRIES=10
BUY_SLIPPAGE=20
```

what am i missing here???

**Comment by khalilshamdan** [comment]
ok i figured it out, but cant delete my issue

**Comment by piotrdewastator** [comment]
whats wrong ? i have that same

**Comment by iSte94** [comment]
Same problem, how to solve?

**Comment by khalilshamdan** [comment]
you can directly change SOL to WSOL one DeFi site, i forgot which one but it was mentioned in another closed issue.
