### ISSUE TITLE
Some feedback, some questions

### ISSUE THREAD

**Issue by mikesens** [warp-id/solana-trading-bot#20]
#Not pro coder feedback

Just wanted to drop some feedback. This code I've been testing from open sources is rock solid, delivering the best results I've seen yet (pool detection speed). The author is pure gold. I've put it through its paces with various public nodes and geos (like Helius, which spans multiple regions/countries, though exact city details are scarce).

Observations:

+ The code's performing well, swap is almost instant (depends on node/load)
+ Instant pool detection (for instant pool detection tx commitment = ```confirmed```  -> ```processed```
- makeSwapFixedInInstruction sometimes misses when passing new poolKeys

Would be awesome if @fdundjer or other contributors would prompt how to build 'sell-after' function

p.s. If someone is looking to integrate basic pool/token info to filter out scam pools (liquidity, authority, Raydium supply, top holders, and socials), below are my findings as far:

1) Liquidity amount: ```QuoteVault``` is probably where its stored. ```getBalance``` method can be used to obtain LP in Sol.
2) Supply/Top holders%/Raydiyum%: raw data can be obtained using ```getTokenSupply``` / ```getTokenLargestAccounts``` / ```getParsedAccountInfo```
3) Mint/Freeze authority authority, deployer info can be decoded from account data: ```https://www.helius.dev/blog/solana-dev-101-deserializing-account-data-on-solana```

BR

**Comment by fdundjer** [comment]
@mikesens Thanks for kind words.
Playing around with commitment level increases detection speed, but some transactions may not succeed. 
I set a default value to finalized to lower the amount of reported issues for failed transactions. Got a few of them reported on Discord :(

Regarding new features, it's a tradeoff between performance and functionality.
My initial intention with the script was to be performant. Adding new features will affect that performance. I'll have to think about how to include that.

The sell function is in backlog, I'll add it when I have free time.

**Comment by b-Snaas** [comment]
@mikesens 

I totally agree with your findings. Did you manage to get any further with creating a filter?

**Comment by fdundjer** [comment]
Added new filters in v2. Closing the issue for now
