### ISSUE TITLE
Rugpull safety

### ISSUE THREAD

**Issue by yleyvag** [warp-id/solana-trading-bot#24]
Last night I was playing with the script, it bought like 15 tokens and all of them were rugpulls in less thank a minute, I didn't have a chance to sell before liquidity was taken to zero. Is there any way the buy method can be enhanced to decrease the risk of scam tokens?

**Comment by ngtianxun08** [comment]
How about locked liquidity?

**Comment by mikesens** [comment]
There is no way to do it unless you can snipe block 0-10.
I stopped sniping new pools and switched to manual trading. Those times have passed, I believe.

There are around 1K new pools every day, leading to too many rugs and a decreased RR ratio.
I have tried many custom filters, but still they don't guarantee good tokens, just a slightly increased win ratio.

Would be happy to be wrong on that

**Comment by woodychanjm** [comment]
> There is no way to do it unless you can snipe block 0-10. I stopped bot sniping fresh new pools and switched to manual trading of new tokens. Those times have passed, I believe.
> 
> There are around 1K new pools every day, leading to too many rugs and a decreased RR ratio. I have tried many custom filters, but still they don't guarantee good tokens, just a slightly increased win ratio. The only possible way - pre-defined list of autism or hype related tokens that might have viral effect (like 'joe boden' recently and etc mania), but that's too time consuming.
> 
> Would be happy to be wrong on that

hi @mikesens which tool are you using for the manually trading? I think the website itself is too slow.

**Comment by fdundjer** [comment]
We have added new filers in version 2. Should help with this. I'll close the issue for now.
