### ISSUE TITLE
Check Ownership Renounced and Creator Balance

### ISSUE THREAD

**Issue by ngtianxun** [warp-id/solana-trading-bot#36]
Notice of ownership renunciation and the balance of the creator has some correlation with whether the token will be subject to a rug pull. It's uncertain if there's a way to programmatically check these two factors.

![image](https://github.com/fdundjer/solana-sniper-bot/assets/30182086/0482f99d-8208-4477-a2e8-65ac8f25c7b2)

**Comment by mikesens** [comment]
hi, can you share the link where you see this?
solana explorer?

**Comment by ngtianxun** [comment]
Its birdeye. 
Also, I think social presence plays a significant part. For example, if the token has a website and a Twitter account with a considerable number of subscribers, it normally won't rug pull. This has been my observation so far.

**Comment by fdundjer** [comment]
@ngtianxun Added support for ownership (mint) renounced.
