### ISSUE TITLE
Detect Total Tokens and SOL added to the Pool

### ISSUE THREAD

**Issue by CHToken** [warp-id/solana-trading-bot#46]
Hey guys I've been trying to get the amount added to the pool but the bot usually sends late info.

From the pool, I was able to get the tokens in the LP but that's after trading as started it was not able to get the exact amount but the balance

For example if owner adds 5 SOL to pool on bot sending messages the 5 SOL owner adds might have pumped to 12 Sol before it being sent by the bot to the console

Here is my code line
https://github.com/CHToken/solana-sniper-bot/blob/master/buy.ts

**Comment by CHToken** [comment]
Am I doing something wrong or I need a filter to get the exact amount the owner adds into the pool?

**Comment by nasko94** [comment]
Why is this information important?

**Comment by CHToken** [comment]
To filter rugs token

**Comment by d4op** [comment]
can i simple copy your one over the normal one ?

**Comment by fdundjer** [comment]
Added with new version
