### ISSUE TITLE
Add a filter to check when liquidity is burned / locked

### ISSUE THREAD

**Issue by CHToken** [warp-id/solana-trading-bot#47]
If liquidity is burned or locked, then proceed with buying else don't buy

Can you add this filter to the bot as this will make it more robust when it comes to detecting rugs

**Comment by ui0x** [comment]
+1

**Comment by adam-sami1987** [comment]
Good and important suggestion. I hope dev update it

**Comment by CHToken** [comment]
Is this being worked on?

**Comment by matotubol** [comment]
+1

**Comment by fdundjer** [comment]
Added with new version
