### ISSUE TITLE
HELIUS RPC not worked

### ISSUE THREAD

**Issue by Avlbdv** [warp-id/solana-trading-bot#57]
I added Helius RPC URLs to the .env file, now the bot writes INFO: Buy -- mint, url and dexurl adresses without any errors, but really the Buy does not occur and there are no transactions in Solscan.

RPC_ENDPOINT=https://mainnet.helius-rpc.com/?api-key=[mykey]
RPC_WEBSOCKET_ENDPOINT=wss://mainnet.helius-rpc.com/?api-key=[mykey]

Is it true? What I doing wrong?

**Comment by fdundjer** [comment]
@Avlbdv Can you try new version, it should be fixed?
